# This is a basic workflow to help you get started with Actions

name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ gcloud-config ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  deploy:
    name: Build Front End using Node.js (npm)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flask-server
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/setup-gcloud@main
      with:
          project_id: seraphic-bliss-298801
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          
    - name: Install dependencies
      run: npm install

    - name: Run build
      run: CI=false npm run build
      
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
       credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
       
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        deliverables: app.yaml KGQA  
    - name: Deploy app to GAE ðŸš€
      run: |
          ls
          ls KGQA
          ls
          gcloud app deploy
          
